trigger:
  - master
pr:
  autoCancel: true
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-latest
variables:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

stages:
  - stage: Test
    jobs:
      - job: test_ubuntu
        displayName: Eclipse Temurin
        container: eclipse-temurin:17-jdk-focal
        steps:
          - script: ./mvnw test -T $(nproc)
            displayName: ./mvnw test -T $(nproc)
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              version: 6.0.x
              includePreviewVersions: true
          - task: PublishCodeCoverageResults@1
            displayName: "Code coverage"
            condition: not(eq(variables['Build.Reason'], 'PullRequest'))
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
      - job: maven_3_amazoncorretto_17
        displayName: Amazon Corretto
        steps:
          - script: |
              sed "s/__version__/maven:3-amazoncorretto-17/" -i Dockerfile.amazoncorretto
              docker build -t project -f Dockerfile.amazoncorretto .
            displayName: Build custom amazoncorreto image for Azure Pipelines
          - script: docker run project bash -c "cd /opt/project && ./mvnw test -T $(nproc)"
            displayName: docker run project bash -c "cd /opt/project && ./mvnw test -T $(nproc)"

