trigger:
  - master
pool:
  vmImage: ubuntu-latest
variables:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

stages:
  - stage: Test
    jobs:
      - job: test_ubuntu
        displayName: Eclipse Temurin
        container: eclipse-temurin:17-jdk-focal
        steps:
          - bash: |
              ./mvnw test -T $(nproc)
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              version: 6.0.x
              includePreviewVersions: true
          - task: PublishCodeCoverageResults@1
            displayName: "Code coverage"
            inputs:
              codeCoverageTool: "JaCoCo"
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/target/site/jacoco
              #additionalCodeCoverageFiles: # Optional
              failIfCoverageEmpty: true
      - job: amazon_corretto_17
        displayName: Amazon Corretto
        steps:
          - bash: |
              sed "s/__version__/amazoncorretto:17/" -i Dockerfile.amazoncorretto
              docker build -t project -f Dockerfile.amazoncorretto .
              docker run project bash -c "cd /opt/project && ./mvnw test -T $(nproc)"
